"""Add Users soft delete

Revision ID: 429d459dc4af
Revises: 6bb5e6667623
Create Date: 2019-08-01 06:05:00.596183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429d459dc4af'
down_revision = '6bb5e6667623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
