"""Add email field to Customer

Revision ID: 5037b3bfae4b
Revises: 11f486e4d787
Create Date: 2019-07-28 06:05:05.540575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5037b3bfae4b'
down_revision = '11f486e4d787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_column('customer', 'email')
    # ### end Alembic commands ###
