"""Create User model

Revision ID: 6bb5e6667623
Revises: 85db0d92198a
Create Date: 2019-07-30 05:33:23.446160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bb5e6667623'
down_revision = '85db0d92198a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('admin_privileges_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['admin_privileges_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_admin'), 'users', ['admin'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_modified_at'), 'users', ['modified_at'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customers_last_modified_at'), 'customers', ['last_modified_at'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_photo_url'), 'customers', ['photo_url'], unique=False)
    op.create_index(op.f('ix_customers_surname'), 'customers', ['surname'], unique=False)
    op.drop_index('ix_customer_created_at', table_name='customer')
    op.drop_index('ix_customer_email', table_name='customer')
    op.drop_index('ix_customer_is_deleted', table_name='customer')
    op.drop_index('ix_customer_last_modified_at', table_name='customer')
    op.drop_index('ix_customer_name', table_name='customer')
    op.drop_index('ix_customer_photo_url', table_name='customer')
    op.drop_index('ix_customer_surname', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('surname', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('photo_url', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_customer_surname', 'customer', ['surname'], unique=False)
    op.create_index('ix_customer_photo_url', 'customer', ['photo_url'], unique=False)
    op.create_index('ix_customer_name', 'customer', ['name'], unique=False)
    op.create_index('ix_customer_last_modified_at', 'customer', ['last_modified_at'], unique=False)
    op.create_index('ix_customer_is_deleted', 'customer', ['is_deleted'], unique=False)
    op.create_index('ix_customer_email', 'customer', ['email'], unique=True)
    op.create_index('ix_customer_created_at', 'customer', ['created_at'], unique=False)
    op.drop_index(op.f('ix_customers_surname'), table_name='customers')
    op.drop_index(op.f('ix_customers_photo_url'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_modified_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_modified_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_admin'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
