version: '3'
services:
  debug-backend:
    build:
      context: ../app/
      args:
        username: "nonroot"
    ports:
     - "5001:5000"
     - "5678:5678"
    volumes:
      - ../app:/app
    networks:
      - crm
    command: pipenv run python -m ptvsd --host 0.0.0.0 --port 5678 --wait -m flask run --host 0.0.0.0 --no-reload --with-threads --cert=adhoc

    
networks:
  crm:
    external:
      name: crm
