runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  DATABASE_URI: PRODUCTION_DATABASE_URI
  GOOGLE_LOGIN_CLIENT_ID: YOUR_GOOGLE_LOGIN_CLIENT_ID
  GOOGLE_LOGIN_CLIENT_SECRET: YOUR_GOOGLE_LOGIN_CLIENT_SECRET
  GOOGLE_APPLICATION_CREDENTIALS: YOUR_GOOGLE_APPLICATION_CREDENTIALS
  GOOGLE_PROJECT: YOUR_GOOGLE_PROJECT
  GOOGLE_BUCKET: YOUR_GOOGLE_BUCKET